---
title: Elige una Licencia
description: Una guia practica y sin prejuicios para ayudarte a elegir una licencia.
relative_permalinks: false
markdown: kramdown
url: "https://eligelicencia.github.io/eligeUnaLicencia/"
baseurl: "/eligeUnaLicencia"

collections:
  licenses:
    output: true
    permalink: /licenses/:path/

defaults:
  -
    scope:
      path: ""
      type: "licenses"
    values:
      hidden: true
      layout: license

exclude:
  - app.coffee
  - CNAME
  - CONTRIBUTING.md
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - Rakefile
  - README.md
  - script
  - vendor/bundle
  - test
  - tests
  - assets/vendor/selectivizr/tests
  - assets/vendor/clipboard/test

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-coffeescript

sass:
    style: :compressed

twitter:
  username: "@github"
